language: objective-c
os: osx
before_install:
    - git submodule update --init --recursive
    - gem install net-ssh
    - gem install net-scp
    - brew update
install:
    - brew install ninja
    - brew install boost
script: rake configuration=host_debug project=3rdParty,BtCore,BtMqttSnGateway
