#!/usr/bin/ruby

require 'rake'

def run_sh(cmd)
    sh cmd do |ok, status|
      ok or fail "Command failed with status (#{status.exitstatus}): [#{cmd}]"
	end
end


# ["host_debug","pi_cross_debug","arduino_uno"].each do |configuration|
["host_debug","pi_cross_debug"].each do |configuration|

	cmd =  "rake configuration=#{configuration} project=3rdParty,BtCore,BtMqttSnGateway pi_run_ssh=true"

	puts
	puts "*******************************"
	puts "  #{configuration}"
	puts "*******************************"
	puts

	sh cmd do |ok, status|
      ok or fail "Build of configuration #{configuration} failed with status (#{status.exitstatus}): [#{cmd}]"
	end

end
   